services:
  - docker:20.10.16-dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive  

default:
  image: python:3.9-slim
  before_script:
    - pip install -r etsi_its_msgs/requirements.txt

stages:
  - Generate ROS Messages
  - Build ROS Packages


CAM:
  stage: Generate ROS Messages
  script:
    - >
      ./etsi_its_msgs/scripts/asn1ToRosMsg.py
      ETSI-ITS-ASN1-REDUCED/CAM/CAM-PDU-Descriptions.asn
      ETSI-ITS-ASN1-REDUCED/CAM/ITS-Container.asn
      -o etsi_its_cam_msgs/msg


Build Workspace:
  stage: Build ROS Packages
  image: docker:git
  before_script:
    - apk add --update bash coreutils tar
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
  script:
    - .industrial_ci/gitlab.sh
  variables:
    ROS_DISTRO: noetic
    CATKIN_LINT: 'true'
