etsi2ros:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  trigger:
    include: .gitlab-ci.generate-msgs.yml
    strategy: depend

docker-ros:
  variables:
    DISABLE_ARCH_ARM64: 'true'
  trigger:
    include:
    - project: fb-fi/ops/docker-ros
      ref: main
      file: templates/.gitlab-ci.template.yml
    strategy: depend