default:
  image: python:3.9
  before_script:
    - pip install -r codegen/requirements.txt


stages:
  - ASN1 Reduction
  - ROS Messages
  - Conversion Headers


asn1_reduced_cam:
  stage: ASN1 Reduction
  needs: []
  script:
    - >
      ./codegen/scripts/reduceAsn1ToTypeDependencies.py
      -t CAM
      -o asn1/reduced/cam
      asn1/raw/cam_en302637_2/CAM-PDU-Descriptions.asn
      asn1/raw/cam_en302637_2/cdd/ITS-Container.asn
    - if [[ ! -z "$(git status --porcelain)" ]]; then echo "Code generation script resulted in changes to the repository"; exit 1; fi


etsi_its_cam_msgs:
  stage: ROS Messages
  needs: []
  script:
    - >
      ./codegen/scripts/asn1ToRosMsg.py
      asn1/reduced/cam/CAM-PDU-Descriptions.asn
      asn1/reduced/cam/ITS-Container.asn
      -o etsi_its_msgs/etsi_its_cam_msgs/msg
    - if [[ ! -z "$(git status --porcelain)" ]]; then echo "Code generation script resulted in changes to the repository"; exit 1; fi


etsi_its_cam_conversion:
  stage: Conversion Headers
  needs: []
  script:
    - >
      ./codegen/scripts/asn1ToConversionHeader.py
      asn1/reduced/cam/CAM-PDU-Descriptions.asn
      asn1/reduced/cam/ITS-Container.asn
      -t cam
      -o etsi_its_conversion/etsi_its_cam_conversion/include/etsi_its_cam_conversion
    - if [[ ! -z "$(git status --porcelain)" ]]; then echo "Code generation script resulted in changes to the repository"; exit 1; fi
