Code Generation:
  trigger:
    include: .gitlab-ci.code-generation.yml
    strategy: depend
  variables:
    GIT_SUBMODULE_STRATEGY: recursive

docker-ros:
  trigger:
    include:
    - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/v1.2.0/.gitlab-ci/docker-ros.yml
    strategy: depend
  variables:
    PLATFORM: amd64
    TARGET: dev,run
    BASE_IMAGE: rwthika/ros:latest
    COMMAND: roslaunch etsi_its_conversion start_ConversionNode.launch
    ENABLE_INDUSTRIAL_CI: 'true'
