services:
  - docker:20.10.16-dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive  

default:
  image: python:3.9-slim
  before_script:
    - pip install -r etsi_its_msgs/requirements.txt

stages:
  - Generate ROS Messages
  - Build ROS Packages


CAM:
  stage: Generate ROS Messages
  script:
    - >
      ./etsi_its_msgs/scripts/asn1ToRosMsg.py
      ETSI-ITS-ASN1-REDUCED/CAM/CAM-PDU-Descriptions.asn
      ETSI-ITS-ASN1-REDUCED/CAM/ITS-Container.asn
      -o etsi_its_cam_msgs/msg

DENM:
  stage: Generate ROS Messages
  script:
    - >
      ./etsi_its_msgs/scripts/asn1ToRosMsg.py
      ETSI-ITS-ASN1-REDUCED/DENM/DENM-PDU-Descriptions.asn
      ETSI-ITS-ASN1-REDUCED/DENM/ITS-Container.asn
      -o etsi_its_denm_msgs/msg

EVCSN:
  stage: Generate ROS Messages
  script:
    - >
      ./etsi_its_msgs/scripts/asn1ToRosMsg.py
      ETSI-ITS-ASN1-REDUCED/EVCSN/EVCSN-PDU-Descriptions.asn
      ETSI-ITS-ASN1-REDUCED/EVCSN/ITS-Container.asn
      -o etsi_its_evcsn_msgs/msg

EVRSR:
  stage: Generate ROS Messages
  script:
    - >
      ./etsi_its_msgs/scripts/asn1ToRosMsg.py
      ETSI-ITS-ASN1-REDUCED/EVRSR/EV-RSR-PDU-Descriptions.asn
      ETSI-ITS-ASN1-REDUCED/EVRSR/ITS-Container.asn
      -o etsi_its_evrsr_msgs/msg

MAPEM:
  stage: Generate ROS Messages
  script:
    - >
      ./etsi_its_msgs/scripts/asn1ToRosMsg.py
      ETSI-ITS-ASN1-REDUCED/MAPEM/MAPEM-PDU-Descriptions.asn
      ETSI-ITS-ASN1-REDUCED/MAPEM/ITS-Container.asn
      ETSI-ITS-ASN1-REDUCED/MAPEM/ISO-TS-19091-addgrp-C-2018.asn
      -o etsi_its_mapem_msgs/msg

SPATEM:
  stage: Generate ROS Messages
  script:
    - >
      ./etsi_its_msgs/scripts/asn1ToRosMsg.py
      ETSI-ITS-ASN1-REDUCED/SPATEM/SPATEM-PDU-Descriptions.asn
      ETSI-ITS-ASN1-REDUCED/SPATEM/ITS-Container.asn
      ETSI-ITS-ASN1-REDUCED/SPATEM/ISO-TS-19091-addgrp-C-2018.asn
      -o etsi_its_spatem_msgs/msg


Build Workspace:
  stage: Build ROS Packages
  image: docker:git
  variables:
    ROS_DISTRO: noetic
  before_script:
    - apk add --update bash coreutils tar
    - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci .industrial_ci -b master
  script:
    - .industrial_ci/gitlab.sh
